#pragma config(Sensor, in7,    potArm,         sensorPotentiometer)
#pragma config(Sensor, in8,    potFlipFlop,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           mogoL,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           df,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           db,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           flipflop,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           armR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           chump,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           pf,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           pb,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mogoR,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)


#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#define FLIPFLOPDOWN 1370
#define FLIPFLOPUP 3750

int positions[14]={100, 200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600};
int currentConeCount = 0;

void turnLeft(int power, int time, bool reverse);
void turnRight(int power, int time, bool reverse);

int filter(int input){
	if (input > 20 || input < -20){
		return input;
	}
	else {
		return 0;
	}
}

void closeClaw()
{
	motor[chump] = 127;
	wait1Msec(500);
	motor[chump] = 30;
}

void openClaw()
{
	motor[chump] = -127;
	wait1Msec(500);
	motor[chump] = 0;
}

void assignDriveMotors(int lp, int rp){
		motor[df] = lp;
		motor[db] = lp;
		motor[pf] = rp;
		motor[pb] = rp;
}

void forward(int power, int time){
		assignDriveMotors(power, power);
		wait1Msec(time);
		assignDriveMotors(-10, -10);
		wait1Msec(100);
		assignDriveMotors(0, 0);
}

void backward(int power, int time)
{
	assignDriveMotors(-power,-power);
	wait1Msec(time);
	assignDriveMotors(10,10);
	wait1Msec(100);
	assignDriveMotors(0,0);
}

void turnRight(int power, int time, bool reverse)
{
	if (reverse)
	{
		turnLeft(power,time,false);
		return;
	}
	assignDriveMotors(power,-power);
	wait1Msec(time);
	assignDriveMotors(-10,10);
	wait1Msec(100);
	assignDriveMotors(0,0);
}

void turnLeft(int power, int time, bool reverse)
{
	if (reverse)
	{
		turnRight(power,time,false);
		return;
	}
	assignDriveMotors(-power,power);
	wait1Msec(time);
	assignDriveMotors(10,-10);
	wait1Msec(100);
	assignDriveMotors(0,0);
}

void assignFlipFlop(int power)
{
	motor[flipflop] = power;
}



task drive(){
	while (true){
		int forward = filter(vexRT[Ch3] + vexRT[Ch3Xmtr2]/1.5);
		int turn = filter(vexRT[Ch1] + vexRT[Ch1Xmtr2]/1.5);

		motor[df] = forward + turn;
		motor[db] = forward + turn;
		motor[pf] = forward - turn;
		motor[pb] = forward - turn;
	}
}

void assignArmMotors(int power){
	motor[armL] = power;
	motor[armR] = power;
}

task arm(){
	while(true){
		if(vexRT[Btn6U] == 1 || vexRT[Btn6UXmtr2] == 1){
			assignArmMotors(127);
			while(vexRT[Btn6U] == 1 || vexRT[Btn6UXmtr2] == 1)
			{

			}
			assignArmMotors(8);
		}
		if(vexRT[Btn6D] == 1 || vexRT[Btn6DXmtr2] == 1){
			assignArmMotors(-127);
			while(vexRT[Btn6D] == 1 || vexRT[Btn6DXmtr2] == 1)
			{

			}
			assignArmMotors(0);
        }
        if(vexRT[Btn7L] == 1){
            autoStack(currentConeCount);
            currentConeCount++;
        }
	}
}

void autoStack(int numCones){
	closeClaw();
	assignFlipFlop(127);
	wait1Msec(200);
	assignArmMotors(127);
	int goalPos = positions[numCones-1];
	while(SensorValue[potArm] < goalPos){
		if (SensorValue[potArm] < positions[0] + 400  || SensorValue[potArm] > goalPos - 400){
			assignFlipFlop(127);
		}
		else if (SensorValue[potArm] < goalPos){
			assignFlipFlop(0);
		}
	}
	assignFlipFlop(127);
	while(SensorValue[potFlipFlop] < FLIPFLOPUP){
		//wait
	}
	assignFlipFlop(0);
	assignArmMotors(-40);
	wait1Msec(200);
	openClaw();
	assignArmMotors(127);
	assignFlipFlop(-127);
	wait1Msec(400);
	assignArmMotors(-127);
	while (SensorValue[potArm] > positions[0]){
		if (SensorValue[potFlipFlop] < FLIPFLOPDOWN){
			assignFlipFlop(10);
		}
	}
	if (SensorValue[potFlipFlop] >= FLIPFLOPDOWN){
		assignFlipFlop(-127);
		while (SensorValue[potFlipFlop] >= FLIPFLOPDOWN){
			//wait
		}
		assignFlipFlop(10);
	}
}

void assignMogoMotors(int power){
	motor[mogoL] = power;
	motor[mogoR] = -power;
}

task mogo(){
	while(true){
		if(vexRT[Btn8U]){
			assignMogoMotors(127);
			while(vexRT[Btn8U])
			{

			}
			assignMogoMotors(0);
		}
		if(vexRT[Btn8D]){
			assignMogoMotors(-127);
			while(vexRT[Btn8D] == 1)
			{

			}
			assignMogoMotors(0);
		}
		if (vexRT[Btn8R]){
			assignMogoMotors(-127);
			wait1Msec(600);
			assignMogoMotors(-70);
			wait1Msec(800);
			assignMogoMotors(-10);
			wait1Msec(400);
			assignMogoMotors(10);
			wait1Msec(300);
			assignMogoMotors(40);
			wait1Msec(300);
			assignMogoMotors(0);
		}
	}
}

task flipfloptask {
	while (true) {
		if (vexRT[Btn5U] || vexRT[Btn5UXmtr2]){
			motor[flipflop] = 127;
			while (vexRT[Btn5U] || vexRT[Btn5UXmtr2]){
				if (SensorValue[potFlipFlop] > FLIPFLOPUP - 250){
					break;
				}
			}
			motor[flipflop] = 0;
			if (SensorValue[potFlipFlop] < FLIPFLOPDOWN + 1000){
				motor[flipflop] = 10;
			} /*else {
				motor[flipflop] = -20;
				wait1Msec(300);
				if (SensorValue[potFlipFlop] > FLIPFLOPUP - 250){
					motor[flipflop] = -10;
				} else {
					motor[flipflop] = 0;
				}
			}*/
		}
		if (vexRT[Btn5D] || vexRT[Btn5DXmtr2]){
			motor[flipflop] = -127;
			while (vexRT[Btn5D] || vexRT[Btn5DXmtr2]){
			}
			if (SensorValue[potFlipFlop] < FLIPFLOPDOWN + 1000){
				motor[flipflop] = 10;
			} else {
				motor[flipflop] = 0;
			}
			motor[flipflop] = 10;
		}
		if (vexRT[Btn7R]){
			motor[flipflop] = -127;
			while (SensorValue[potFlipFlop] > FLIPFLOPDOWN){

			}
			motor[flipflop] = 30;
			wait1Msec(100);
			motor[flipflop] = 0;
		}
		if (vexRT[Btn7L]){
			motor[flipflop] = 127;
			while (SensorValue[potFlipFlop] < FLIPFLOPUP){

			}
			motor[flipflop] = 0;
		}
	}
}

task chumptask {
	while (true) {
		if (vexRT[Btn7U] == 1){
			while (vexRT[Btn7U] == 1){
				motor[chump] = 75;
			}
			motor[chump] = 29;
		}
		if (vexRT[Btn7D] == 1){
			while (vexRT[Btn7D] == 1){
				motor[chump] = -75;
			}
			motor[chump] = 0;
		}
	}
}

void pre_auton(){

}

void autonomousConeIn20Pt(bool reverse, bool stopAfterTime)
{
	closeClaw();
	forward(127,300);
	//turnRight(127,250,reverse);
	//turnLeft(127,250,reverse);
	assignArmMotors(127);
	assignMogoMotors(-127);
	forward(127,600);
	assignArmMotors(10);
	wait1Msec(400);
	assignMogoMotors(0);
	forward(127, 650);
	assignMogoMotors(127);
	wait1Msec(1300);
	assignMogoMotors(0);
	wait1Msec(200);
	assignArmMotors(-127);
	wait1Msec(400);
	assignArmMotors(0);
	assignFlipFlop(50);
	wait1Msec(500);
	assignFlipFlop(0);
	openClaw();
	if (stopAfterTime){
		return;
	}
	assignArmMotors(127);
	wait1Msec(600);
	assignArmMotors(10);
	backward(127,1150);
	turnLeft(127,600,reverse);
	backward(80,700);
	forward(127,400);
	turnLeft(127, 530,reverse);
	forward(127, 800);
	turnLeft(127, 450, reverse);
	forward(127, 700);
	assignMogoMotors(-127);
	forward(127, 600);
	wait1Msec(300);
	assignMogoMotors(0);
	backward(127, 1000);
}

task autonomous()
{
	autonomousConeIn20Pt(false, false);
}

task usercontrol(){
	startTask(drive);
	startTask(arm);
	startTask(chumptask);
	startTask(flipfloptask);
	startTask(mogo);
}
