#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in7,    potArm,         sensorPotentiometer)
#pragma config(Sensor, in8,    potFlipFlop,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           mogoL,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           df,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           db,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           flipflop,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           armR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           pf,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           pb,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mogoR,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "autons.c"
#include "helperfunctions.c"

int currentConeCount = 0;

int filter(int input){
	if (input > 20 || input < -20){
		return input;
	}
	else {
		return 0;
	}
}

task drive(){
	while (true){
		int forward = filter(vexRT[Ch3] + vexRT[Ch3Xmtr2]/1.5);
		int turn = filter(vexRT[Ch1] + vexRT[Ch1Xmtr2]/1.5);

		motor[df] = forward + turn;
		motor[db] = forward + turn;
		motor[pf] = forward - turn;
		motor[pb] = forward - turn;
	}
}

task arm(){
	while(true){
		if(vexRT[Btn6U] == 1 || vexRT[Btn6UXmtr2] == 1){
			assignArmMotors(127);
			while(vexRT[Btn6U] == 1 || vexRT[Btn6UXmtr2] == 1)
			{

			}
			assignArmMotors(8);
		}
		if(vexRT[Btn6D] == 1 || vexRT[Btn6DXmtr2] == 1){
			assignArmMotors(-127);
			while(vexRT[Btn6D] == 1 || vexRT[Btn6DXmtr2] == 1)
			{

			}
			assignArmMotors(0);
        }
        if(vexRT[Btn7L] == 1){
            autoStack(currentConeCount);
            currentConeCount++;
        }
	}
}

task mogo(){
	while(true){
		if(vexRT[Btn8U]){
			assignMogoMotors(127);
			while(vexRT[Btn8U])
			{

			}
			assignMogoMotors(0);
		}
		if(vexRT[Btn8D]){
			assignMogoMotors(-127);
			while(vexRT[Btn8D] == 1)
			{

			}
			assignMogoMotors(0);
		}
		if (vexRT[Btn8R]){
			assignMogoMotors(-127);
			wait1Msec(600);
			assignMogoMotors(-70);
			wait1Msec(800);
			assignMogoMotors(-10);
			wait1Msec(400);
			assignMogoMotors(10);
			wait1Msec(300);
			assignMogoMotors(40);
			wait1Msec(300);
			assignMogoMotors(0);
		}
	}
}

task flipfloptask {
	while (true) {
		if (vexRT[Btn5U] || vexRT[Btn5UXmtr2]){
			motor[flipflop] = 127;
			while (vexRT[Btn5U] || vexRT[Btn5UXmtr2]){
				if (SensorValue[potFlipFlop] > FLIPFLOPUP - 250){
					break;
				}
			}
			motor[flipflop] = 0;
			if (SensorValue[potFlipFlop] < FLIPFLOPDOWN + 1000){
				motor[flipflop] = 10;
			} /*else {
				motor[flipflop] = -20;
				wait1Msec(300);
				if (SensorValue[potFlipFlop] > FLIPFLOPUP - 250){
					motor[flipflop] = -10;
				} else {
					motor[flipflop] = 0;
				}
			}*/
		}
		if (vexRT[Btn5D] || vexRT[Btn5DXmtr2]){
			motor[flipflop] = -127;
			while (vexRT[Btn5D] || vexRT[Btn5DXmtr2]){
			}
			if (SensorValue[potFlipFlop] < FLIPFLOPDOWN + 1000){
				motor[flipflop] = 10;
			} else {
				motor[flipflop] = 0;
			}
			motor[flipflop] = 10;
		}
		if (vexRT[Btn7R]){
			motor[flipflop] = -127;
			while (SensorValue[potFlipFlop] > FLIPFLOPDOWN){

			}
			motor[flipflop] = 30;
			wait1Msec(100);
			motor[flipflop] = 0;
		}
		if (vexRT[Btn7L]){
			motor[flipflop] = 127;
			while (SensorValue[potFlipFlop] < FLIPFLOPUP){

			}
			motor[flipflop] = 0;
		}
	}
}

task clawtask {
	while (true) {
		if (vexRT[Btn7U] == 1){
			while (vexRT[Btn7U] == 1){
				motor[claw] = 75;
			}
			motor[claw] = 29;
		}
		if (vexRT[Btn7D] == 1){
			while (vexRT[Btn7D] == 1){
				motor[claw] = -75;
			}
			motor[claw] = 0;
		}
	}
}

task coneCounter(){
	while (true){
		if (vexRT[Btn7DXmtr2]){
			currentConeCount = 3;
		}
		if (vexRT[Btn7LXmtr2]){
			currentConeCount = 6;
		}
		if (vexRT[Btn7UXmtr2]){
			currentConeCount = 9;
		}
		if (vexRT[Btn7RXmtr2]){
			currentConeCount = 12;
		}
		if (vexRT[Btn8DXmtr2]){
			currentConeCount = 0;
		}
		if (vexRT[Btn8LXmtr2]){
			currentConeCount--;
		}
		if (vexRT[Btn8RXmtr2]){
			currentConeCount++;
		}
	}
}

void pre_auton(){
	SensorType[gyro] = sensorNone;
	wait1Msec(2000);
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);
}

task autonomous()
{
	autonomousConeIn20Pt(false, false);
}

task usercontrol(){
	startTask(drive);
	startTask(arm);
	startTask(clawtask);
	startTask(flipfloptask);
	startTask(mogo);
	startTask(coneCounter);
}
